export const images_of_flags = {
    mexico: require('../assets/FlagsCountries/mexico.png'),
    brasil: require('../assets/FlagsCountries/brasil.png'),
    panama: require('../assets/FlagsCountries/panama.png'),
    ecuador: require('../assets/FlagsCountries/ecuador.png'),
    colombia: require('../assets/FlagsCountries/colombia.png'),
    argentina: require('../assets/FlagsCountries/argentina.png'),
    guatemala: require('../assets/FlagsCountries/guatemala.png'),
    reino_unido: require('../assets/FlagsCountries/reino-unido.png'),
    union_europea: require('../assets/FlagsCountries/union-europea.png'),
    estados_unidos: require('../assets/FlagsCountries/estados-unidos.png'),

    bolivia: require('../assets/FlagsCountries/default.png'),
    belice: require('../assets/FlagsCountries/default.png'),
    china: require('../assets/FlagsCountries/default.png'),
    japon: require('../assets/FlagsCountries/default.png'),
    corea_sur: require('../assets/FlagsCountries/default.png'),
    corea_norte: require('../assets/FlagsCountries/default.png'),
};

export const countries = [
    {
        code: 'GTQ',
        exchange: '',
        name: 'Quetzal',
        country: 'Guatemala',
        flag: 'guatemala',
        convert: '',
    },
    {
        code: 'USD',
        exchange: '',
        name: 'Dólar estadounidense',
        country: 'Estados Unidos',
        flag: 'estados_unidos',
        convert: '',
    },
    {
        code: 'EUR',
        exchange: '',
        name: 'Euro',
        country: 'UNION EUROPE',
        flag: 'union_europea',
        convert: '',
    },
    {
        code: 'CNY',
        exchange: '',
        name: 'Renminbi',
        country: 'CHINA',
        flag: 'china',
        convert: '',
    },
    {
        code: 'GBP',
        exchange: '',
        name: 'Libra esterlina	',
        country: 'REINO UNIDO DE GRAN BRETAÑA',
        flag: 'reino_unido',
        convert: '',
    },
    {
        code: 'ARS',
        exchange: '',
        name: 'Peso argentino',
        country: 'ARGENTINA',
        flag: 'argentina',
        convert: '',
    },
    {
        code: 'COP',
        exchange: '',
        name: 'Peso colombiano',
        country: 'COLOMBIA',
        flag: 'colombia',
        convert: '',
    },
    {
        code: 'MXN',
        exchange: '',
        name: 'Mexico',
        country: 'Peso mexicano',
        flag: 'mexico',
        convert: '',
    },
    {
        code: 'BZD',
        exchange: '',
        name: 'Dólar beliceño',
        country: 'BELICE',
        flag: 'belice',
        convert: '',
    },
    {
        code: 'BOB',
        exchange: '',
        name: 'Boliviano',
        country: 'BOLIVIA',
        flag: 'bolivia',
        convert: '',
    },
    {
        code: 'BRL',
        exchange: '',
        name: 'Real brasileño',
        country: 'BRASIL',
        flag: 'brasil',
        convert: '',
    },
    {
        code: 'PAB',
        exchange: '',
        name: 'Balboa',
        country: 'PANAMÁ',
        flag: 'panama',
        convert: '',
    },
    {
        code: 'USD',
        exchange: '',
        name: 'Dólar estadounidense',
        country: 'ECUADOR',
        flag: 'ecuador',
        convert: '',
    },
    {
        code: 'JPY',
        exchange: '',
        name: 'Yen',
        country: 'JAPÓN',
        flag: 'japon',
        convert: '',
    },
    {
        code: 'KRW',
        exchange: '',
        name: 'Won',
        country: 'COREA DEL SUR',
        flag: 'corea_sur',
        convert: '',
    },
    {
        code: 'KPW',
        exchange: '',
        name: 'Won norcoreano',
        country: 'COREA DEL NORTE',
        flag: 'corea_norte',
        convert: '',
    },
    // {
    //     code: '',
    //     exchange: '',
    //     name: '',
    //     country: '',
    //     flag: '',
    // },
];